services:
  fluentd:
    image: fluent/fluentd:v1.15.1-1.0
    # 設定ファイルでなくコマンドで指定したい場合
    # command: --worker 4
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 24226:24226
